
class OrderStatus:
  OPEN = "OPEN"
  COMPLETE = "COMPLETE"
  OPEN_PENDING = "OPEN PENDING"
  VALIDATION_PENDING = "VALIDATION PENDING"
  PUT_ORDER_REQ_RECEIVED = "PUT ORDER REQ RECEIVED"
  TRIGGER_PENDING = "TRIGGER PENDING"
  REJECTED = "REJECTED"
  CANCELLED = "CANCELLED"
  